### ISSUE TITLE
7. List the members of the batch (read BatchRegistry contract)

### ISSUE THREAD

**Issue by edakturk14** [BuidlGuidl/batch8.buidlguidl.com#4]
## Goal

Show the current members of your batch in the app.

- Show it on the main page or create a page (/builders) listing all the builders registered in the BatchRegistry contract (see #10)
- Each builder should link to their personal profile (see #9)

**Comment by rohan-ahire06** [comment]
Hey! I completed my #1 and #9 (# 2) issues, and I would love to work on this one. 

#1
<img width="904" alt="image" src="https://github.com/user-attachments/assets/f8200451-8d44-4578-88d0-d242493a5611">


#9 
![image](https://github.com/user-attachments/assets/df65756f-14e6-4eed-803c-8661a2e286d8)

**Comment by rohan-ahire06** [comment]
I've completed the UI for the Builders page. added the Builders option to the navbar. The design is ready for review. Let me know if there are any changes I have to do.


<img width="1710" alt="Screenshot 2024-08-14 at 11 31 19 AM" src="https://github.com/user-attachments/assets/0e40c8c0-b735-40c5-a085-0d8181bfcc54">

**Comment by derrekcoleman** [comment]
Hey @rohan-ahire06! Thanks for including a screenshot of your proposed design. That makes feedback much easier.

I recommend you format this as a table so that it's easier to read and because there's more information to display for each address (see below). I see you're using an address component for each builder. The default behavior (i.e. what users might expect) for clicking a component like that is to copy the user's address, sometimes even to take them to the block explorer for that address. However, this issue has the requirement that 
> Each builder should link to their personal profile

so you'll need to show more explicitly that a user can click somewhere to go to each addresses's builder page.

Also, not everyone has finished making their builder page yet. So after you fetch the addresses you'll also have to check if _each_ one has a builder page or not, then display the appropriate state on the UI.
